#!/bin/bash

# pacint - interactive pacman and yay wrapper

case $1 in

    "-i"|"--install")
        # install package
        query=$(yay -Slq | fzf --preview 'yay -Si {}' --layout=reverse)
        case $query in
            
            "")
                printf "\033[01;31merror:\033[0m no package name returned\n"
                exit 1
            ;;
                
            $(pacman -Slq | grep -i ^$query$))
                sudo pacman -S $query
            ;;
                
            $(yay -Slqa | grep -i ^$query$))
                yay -S --removemake $query
            ;;
                
            *)
                printf "\033[01;31merror:\033[0m package not found\n"
                exit 1
            ;;
            
        esac
        ;;
        
    "-r"|"--remove")
        # remove package
        query=$(pacman -Qq | fzf --preview 'pacman -Si {}' --layout=reverse)
        if [[ -n $query ]]; then
            sudo pacman -Runs $query
        else
            printf "\033[01;31merror:\033[0m no package name returned\n"
            exit 1
        fi
        ;;
        
    "-s"|"--search")
        # search without installing
        yay -Slq | fzf --preview 'yay -Si {}' --layout=reverse
        ;;
        
    "-l"|"--list")
        # search installed packages
        pacman -Qq | fzf --preview 'pacman -Si {}' --layout=reverse
        ;;
        
    "-u"|"--update")
        # update packages
        printf "\nupdating all packages\n"
        printf '\n%*s\n\n' "${COLUMNS:-$(tput cols)}" "pacman  " | tr ' ' =
        sudo pacman -Syu
        printf '\n%*s\n\n' "${COLUMNS:-$(tput cols)}" "yay  " | tr ' ' =
        yay -Syua --removemake
        printf '\n%*s\n\n' "${COLUMNS:-$(tput cols)}" "" | tr ' ' =
        printf "all updates complete\n\n"
        ;;
        
    "-c"|"--clean")
        # cleanup package cache and unused repositoried
        sudo pacman -Sc
        printf "\n"
        yay -Sca
        ;;
        
    "-o"|"--orphans")
        if [[ -n $(pacman -Qtdq) ]]; then
            pacman -Qtdq
        else 
            printf "no orphan packages found\n"
        fi
        ;;
        
    "-O"|"--removeorphans")
        if [[ -n $(pacman -Qtdq) ]]; then
            sudo pacman -Runs $(pacman -Qtdq | sed "s/\n/ /g")
            printf "orphan packages removed\n"
        else
            printf "no orphan packages found\n"
        fi
        ;;
        
    "-h"|"--help")
        # display help page
        printf "usage: pacint <operation>\n"
        printf "operations:\n"
        printf "    -i, --install       install packages\n"
        printf "    -r, --remove        remove packages\n"
        printf "    -s, --search        search without installing\n"
        printf "    -l, --list          search installed packages\n"
        printf "    -u, --update        update packages\n"
        printf "    -c, --clean         cleanup package cache and unused repositories\n"
        printf "    -o, --orphans       list orphan packages\n"
        printf "    -O, --removeorphans remove orphan packages\n"
        printf "    -h, --help          display this help page\n"
        ;;
        
    "")
        printf "\033[01;31merror:\033[0m no operation specified (use -h for help)\n"
        exit 2
        ;;
        
    *)
        printf "\033[01;31merror:\033[0m invalid operation '$1' (use -h for help)\n"a
        exit 2
        ;;
        
esac
