#!/bin/bash

case $1 in

    "-i"|"--install")
        # install
        sudo pacman -S $(pacman -Slq | fzf --preview 'pacman -S {}' --layout=reverse)
        ;;

    "-a"|"--aur")
        # install from aur
        yay -S $(yay -Slq | fzf --preview 'yay -Si {}' --layout=reverse)
        ;;
        
    "-r"|"--remove")
        #remove
        sudo pacman -Runcs $(pacman -Qq | fzf --preview 'pacman -Si {}' --layout=reverse)
        ;;

    "-I")
        # search without installing
        sudo pacman -Slq | fzf --preview "pacman -S {}" --layout=reverse
        ;;

    "-A")
        # search AUR without installing
        yay -Slq | fzf --preview 'yay -Si {}' --layout=reverse
        ;;

    "-h"|"--help")
        echo "usage: pacint <operation>"
        echo "operations:"
        echo "    -i, --install  install packages"
        echo "    -a, --aur      install aur packages"
        echo "    -r, --remove   remove packages"
        echo "    -I             search without installing"
        echo "    -A             search aur without installing"
        echo "    -h, --help     display this help page"
        ;;
        
    "")
        printf "\033[01;31merror:\033[0m no operation specified (use -h for help)\n"
        ;;

    *)
        printf "\033[01;31merror:\033[0m invalid option '$1' (use -h for help)\n"
        ;;

esac
