#!/bin/bash

case $1 in

    "-i"|"--install")
        # install
        sudo pacman -S $(pacman -Slq | fzf --preview 'pacman -Si {}' --layout=reverse)
        ;;

    "-a"|"--aur")
        # install from aur
        yay -S $(yay -Slq | fzf --preview 'yay -Si {}' --layout=reverse)
        ;;
        
    "-r"|"--remove")
        #remove
        sudo pacman -Runcs $(pacman -Qq | fzf --preview 'pacman -Si {}' --layout=reverse)
        ;;

    "-S"|"--search")
        # search without installing
        sudo pacman -Slq | fzf --preview "pacman -Si {}" --layout=reverse
        ;;

    "-A")
        # search AUR without installing
        yay -Slq | fzf --preview 'yay -Si {}' --layout=reverse
        ;;

    "-I")
        # search installed packages
        pacman -Qqe | fzf --preview 'pacman -Si {}' --layout=reverse
        ;;

    "-u"|"--update")
        # update packages
        sudo pacman -Syu
        echo ""
        yay -Sua
        ;;

    "-h"|"--help")
        # display help page
        printf "usage: pacint <operation>\n"
        printf "operations:\n"
        printf "    -i, --install  install packages\n"
        printf "    -a, --aur      install aur packages\n"
        printf "    -r, --remove   remove packages\n"
        printf "    -S, --search   search without installing\n"
        printf "    -A             search aur without installing\n"
        printf "    -I             search instaled packages\n"
        printf "    -u, --update   update packages\n"
        printf "    -h, --help     display this help page\n"
        ;;
        
    "")
        printf "\033[01;31merror:\033[0m no operation specified (use -h for help)\n"
        ;;

    *)
        printf "\033[01;31merror:\033[0m invalid operation '$1' (use -h for help)\n"
        ;;

esac
